export default class CommonConstants {

  static readonly FULL_PARENT: string = '100%';
  static readonly NINETY_PARENT: string = '90%';
  static readonly EIGHTY_PARENT: string = '80%';
  static readonly HALF_PARENT: string = '50%';
  static readonly FORTY_PERCENT: string = '40%';
  static readonly FULL_PARENT_HALF: string = '150%';
  static readonly DOUBLE_PARENT: string = '200%';
  static readonly PARENT_NINETY_FIVE: string = '95%';
  static readonly PARENT_FIFTY_ONE: string = '51%';
  static readonly PARENT_NINETY_SEVEN: string = '97%'
}